import Head from 'next/head';

export default function Indicador(props) {    
    const data = props.data;
    const indicadores = data.map(indicador => {
        return <li>{indicador.nombre}</li>
    });

    return (
        <div>
            <Head>
                <title>Indicadores</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>Indicadores - Modulo</h1>
            <ul>{indicadores}</ul>
        </div>
    );
};

export async function getServerSideProps(context) {
    const idModulo = context.params.idIndicador;
    const res = await fetch(`${process.env.INDICADORES_BASE_URL}/modulos/${idModulo}/indicadores`);
    const data = await res.json();
    if (res.status === 200) {
        return {
            props: { ...data }
        }
    } else
        return {
            props: {
                data: []
            }
        }

    return {
        props:{},
    }
};