import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Container from "@mui/material/Container";
import EmblaCarousel from '@components/EmblaCarousel';
import Footer from '@components/Footer';
import GridBase from '@components/ProjectCard/GridBase';


export default function Home() {
  return (
    <>
      <EmblaCarousel />
    <div className={styles.container}>
      <Head>
        <title>Observatorio urbano</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <h1>Observatorio Urbano</h1>
        <GridBase />
      </Container>
      </div>
    </>
  )
}
